/* GLOBAL ACTIONS */
export const FETCHING = 'FETCHING'
export const FETCH_SUCCES = 'FETCH_SUCCES'
export const FETCH_FAIL = 'FETCH_FAIL'
export const CLEAR_ERROR_MESSAGE = 'CLEAR_ERROR_MESSAGE'

/* USER ACTIONS */
export const FETCHING_USER = 'FETCHING_USER'
export const FETCH_USER_SUCCES = 'FETCH_USER_SUCCES'
export const FETCH_USER_FAIL = 'FETCH_USER_FAIL'

export const LOGGING_IN = 'LOGGING_IN'
export const LOG_IN_SUCCESS = 'LOG_IN_SUCCESS'
export const LOG_IN_FAIL = 'LOG_IN_FAIL'
export const LOG_OUT = 'LOG_OUT'

export const UPDATING_USER = 'UPDATING_USER'
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS'
export const UPDATE_USER_FAIL = 'UPDATE_USER_FAIL'


/* PRODUCT ACTIONS */
export const FETCHING_PRODUCTS = 'FETCHING_PRODUCTS'
export const FETCH_PRODUCTS_SUCCESS = 'FETCH_PRODUCTS_SUCCESS'
export const FETCH_PRODUCTS_FAIL = 'FETCH_PRODUCTS_FAIL'

export const FETCHING_PRODUCT = 'FETCHING_PRODUCT'
export const FETCH_PRODUCT_SUCCESS = 'FETCH_PRODUCT_SUCCESS'
export const FETCH_PRODUCT_FAIL = 'FETCH_PRODUCT_FAIL'

export const SET_CURRENT_PRODUCT = 'SET_CURRENT_PRODUCT'

export const FETCHING_RELATED_PRODUCTS = 'FETCHING_RELATED_PRODUCTS'
export const FETCH_RELATED_SUCCESS = 'FETCH_RELATED_SUCCESS'
export const FETCH_RELATED_FAIL = 'FETCH_RELATED_FAIL'

export const SET_SEARCH_TERM = 'SET_SEARCH_TERM'

export const CLEAR_PRODUCT_SEARCH_RESULTS = 'CLEAR_PRODUCT_SEARCH_RESULTS'


/* LOCATION ACTIONS */
export const FETCHING_LOCATION = 'FETCHING_LOCATION'
export const FETCH_LOCATION_SUCCES = 'FETCH_LOCATION_SUCCES'
export const FETCH_LOCATION_FAIL = 'FETCH_LOCATION_FAIL'

export const FETCHING_LOCATIONS = 'FETCHING_LOCATIONS'
export const FETCH_LOCATIONS_SUCCES = 'FETCH_LOCATIONS_SUCCES'
export const FETCH_LOCATIONS_FAIL = 'FETCH_LOCATIONS_FAIL'

export const SET_CURRENT_STORE = 'SET_CURRENT_STORE'
export const SET_CHANGING_HOME_STORE = 'SET_CHANGING_HOME_STORE'

export const SET_SEARCH_ZIP = 'SET_ZIP'

export const CLEAR_LOCATION_LIST = 'CLEAR_LOCATION_LIST'

export const SETTING_HOME_STORE = 'SETTING_HOME_STORE'
export const SET_HOME_STORE_SUCCESS = 'SET_HOME_STORE_SUCCESS'
export const SET_HOME_STORE_FAIL = 'SET_HOME_STORE_FAIL'

/* CART ACTIONS */
export const FETCHING_CART = 'FETCHING_CART'
export const FETCH_CART_SUCCES = 'FETCH_SUCCES'
export const FETCH_CART_FAIL = 'FETCH_FAIL'

export const ADD_ITEM_TO_CART = 'ADD_ITEM_TO_CART'
export const REMOVE_ITEM_FROM_CART = 'REMOVE_ITEM_FROM_CART'
export const CHANGE_ITEM_QUANTITY = 'CHANGE_ITEM_QUANTITY'

export const CLEAR_CART = 'CLEAR_CART'

export const POSTING_CART = 'POSTING_CART'
export const POSTING_CART_SUCCESS = 'POSTING_CART_SUCCESS'
export const POSTING_CART_FAIL = 'POSTING_CART_FAIL'


/* RECIPE ACTOINS */
export const FETCHING_RECIPES = 'FETCHING_RECIPES'
export const FETCH_RECIPES_SUCCESS = 'FETCH_RECIPES_SUCCESS'
export const FETCH_RECIPES_FAIL = 'FETCH_RECIPES_FAIL'

export const FETCHING_RECIPE = 'FETCHING_RECIPE'
export const FETCH_RECIPE_SUCCESSS = 'FETCH_RECIPE_SUCCESS'
export const FETCH_RECIPE_FAIL = 'FETCH_RECIPE_FAIL'

export const FETCHING_INGREDIENTS = 'FETCHING_INGREDIENTS'
export const FETCH_INGREDIENTS_SUCCESS = 'FETCH_INGREDIENTS_SUCCESS'
export const FETCH_INGREDIENTS_FAIL = 'FETCH_INGREDIENTS_FAIL'

export const CREATING_RECIPE = 'CREATING_RECIPE'
export const CREATE_RECIPE_SUCCESS = 'CREATE_RECIPE_SUCCESS'
export const CREATE_RECIPE_FAIL = 'CREATE_RECIPE_FAIL'

export const CREATING_INGREDIENT = 'CREATING_INGREDIENT'
export const CREATE_INGREDIENT_SUCCESS = 'CREATE_INGREDIENT_SUCCESS'
export const CREATE_INGREDIENT_FAIL = 'CREATE_INGREDIENT_FAIL'

export const CREATING_STEP = 'CREATING_STEP'
export const CREATE_STEP_SUCCESS = 'CREATE_STEP_SUCCESS'
export const CREATE_STEP_FAIL = 'CREATE_STEP_FAIL'

export const UPDATING_RECIPE = 'UPDATING_RECIPE'
export const UPDATE_RECIPE_SUCCESS = 'UPDATE_RECIPE_SUCCESS'
export const UPDATE_RECIPE_FAIL = 'UPDATE_RECIPE_FAIL'

export const UPDATING_INGREDIENT = 'UPDATING_INGREDIENT'
export const UPDATE_INGREDIENT_SUCCESS = 'UPDATE_INGREDIENT_SUCCESS'
export const UPDATE_INGREDIENT_FAIL = 'UPDATE_INGREDIENT_FAIL'

export const UPDATING_STEP = 'UPDATING_STEP'
export const UPDATE_STEP_SUCCESS = 'UPDATE_STEP_SUCCESS'
export const UPDATE_STEP_FAIL = 'UPDATE_STEP_FAIL'

export const DELETING_RECIPE = 'DELETING_RECIPE'
export const DELETE_RECIPE_SUCCESS = 'DELETE_RECIPE_SUCCESS'
export const DELETE_RECIPE_FAIL = 'DELETE_RECIPE_FAIL'

export const DELETING_INGREDIENT = 'DELETING_INGREDIENT'
export const DELETE_INGREDIENT_SUCCESS = 'DELETE_INGREDIENT_SUCCESS'
export const DELETE_INGREDIENT_FAIL = 'DELETE_INGREDIENT_FAIL'

export const DELETING_STEP = 'DELETING_STEP'
export const DELETE_STEP_SUCCESS = 'DELETE_STEP_SUCCESS'
export const DELETE_STEP_FAIL = 'DELETE_STEP_FAIL'

// non async
export const SET_CURRENT_RECIPE =  'SET_CURRENT_RECIPE'
export const SET_CURRENT_INGREDIENT = 'SET_CURRENT_INGREDIENT'
export const SET_CURRENT_STEP = 'SET_CURRENT_STEP'

export const EDITNIG_RECIPE_HEADER = 'EDITNIG_RECIPE_HEADER'
export const EDITING_INGREDIENT = 'EDITING_INGREDIENT'
export const EDITING_STEP = 'EDITING_STEP'

export const RESET_RECIPE = 'RESET_RECIPE'

export const SET_SEARCHING_INGREDIENT = 'SET_SEARCHING_INGREDIENT'
export const SET_EDITING_MODE = 'SET_EDITING_MODE'
