/* GLOBAL ACTIONS */
export const FETCHING = 'FETCHING'
export const FETCH_SUCCES = 'FETCH_SUCCES'
export const FETCH_FAIL = 'FETCH_FAIL'
export const CLEAR_ERROR_MESSAGE = 'CLEAR_ERROR_MESSAGE'

/* USER (account) ACTIONS */
export const FETCHING_USER = 'FETCHING_USER'
export const FETCH_USER_SUCCES = 'FETCH_USER_SUCCES'
export const FETCH_USER_FAIL = 'FETCH_USER_FAIL'

export const LOGGING_IN = 'LOGGING_IN'
export const LOG_IN_SUCCESS = 'LOG_IN_SUCCESS'
export const LOG_IN_FAIL = 'LOG_IN_FAIL'
export const LOG_OUT = 'LOG_OUT'

export const UPDATING_USER = 'UPDATING_USER'
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS'
export const UPDATE_USER_FAIL = 'UPDATE_USER_FAIL'

/* INTERDEPENDANT ACTIONS */
export const FETCHING_FLATTENED_ROUTINE = "FETCHING_FLATTENED_ROUTINE"
export const FETCH_FLATTENED_ROUTINE_SUCCESS = "FETCH_FLATTENED_ROUTINE_SUCCESS"
export const FETCH_FLATTENED_ROUTINE_FAIL = "FETCH_FLATTENED_ROUTINE_FAIL"

/* EXERCISE ACTIONS */
export const SET_CURRENT_EXERCISE= "SET_CURRENT_EXERCISE"
export const WRITING_EXERCISE = "WRITING_EXERCISE"
export const CLEAR_CURRENT_EXERCISE = "CLEAR_CURRENT_EXERCISE"
export const INITIATE_EXERCISE = "INITIATE_EXERCISE"

// async
export const CREATING_EXERCISE = 'CREATING_EXERCISE'
export const CREATE_EXERCISE_SUCCESS = 'CREATE_EXERCISE_SUCCESS'
export const CREATE_EXERCISE_FAIL = 'CREATE_EXERCISE_FAIL'

export const UPDATING_EXERCISE = 'UPDATING_EXERCISE'
export const UPDATE_EXERCISE_SUCCESS = 'UPDATE_EXERCISE_SUCCESS'
export const UPDATE_EXERCISE_FAIL = 'UPDATE_EXERCISE_FAIL'

export const FETCHING_EXERCISES = 'FETCHING_EXERCISES'
export const FETCH_EXERCISES_SUCCESS = 'FETCH_EXERCISES_SUCCESS'
export const FETCH_EXERCISES_FAIL = 'FETCH_EXERCISES_FAIL'

export const SEARCHING_EXERCISES = 'SEARCHING_EXERCISES'
export const SEARCH_EXERCISES_SUCCESS = 'SEARCH_EXERCISES_SUCCESS'
export const SEARCH_EXERCISES_FAIL = 'SEARCH_EXERCISES_FAIL'
export const CLEAR_EXERCISE_SEARCH_RESULTS = "CLEAR_EXERCISE_SEARCH_RESULTS"

export const FETCHING_EXERCISE = 'FETCHING_EXERCISE'
export const FETCH_EXERCISE_SUCCESS = 'FETCH_EXERCISE_SUCCESS'
export const FETCH_EXERCISE_FAIL = 'FETCH_EXERCISE_FAIL'

export const DELETING_EXERCISE = 'DELETING_EXERCISE'
export const DELETE_EXERCISE_SUCCESS = 'DELETE_EXERCISE_SUCCESS'
export const DELETE_EXERCISE_FAIL = 'DELETE_EXERCISE_FAIL'


/* ROUTINE ACTIONS */
export const SET_CURRENT_ROUTINE = "SET_CURRENT_ROUTINE"
export const WRITING_ROUTINE = "WRITING_ROUTINE"
export const CLEAR_CURRENT_ROUTINE="CLEAR_CURRENT_ROUTINE"
export const CLEAR_ROUTINE_SEARCH_RESULTS = "CLEAR_ROUTINE_SEARCH_RESULTS"
export const INITIATE_ROUTINE = "INITIATE_ROUTINE"

// asnync
export const CREATING_ROUTINE = 'CREATING_ROUTINE'
export const CREATE_ROUTINE_SUCCESS = 'CREATE_ROUTINE_SUCCESS'
export const CREATE_ROUTINE_FAIL = 'CREATE_ROUTINE_FAIL'

export const FETCHING_ROUTINES = 'FETCHING_ROUTINES'
export const FETCH_ROUTINES_SUCCESS = 'FETCH_ROUTINES_SUCCESS'
export const FETCH_ROUTINES_FAIL = 'FETCH_ROUTINES_FAIL'

export const FETCHING_ROUTINE = 'FETCHING_ROUTINE'
export const FETCH_ROUTINE_SUCCESS = 'FETCH_ROUTINE_SUCCESS'
export const FETCH_ROUTINE_FAIL = 'FETCH_ROUTINE_FAIL'

export const UPDATING_ROUTINE = 'UPDATING_ROUTINE'
export const UPDATE_ROUTINE_SUCCESS = 'UPDATE_ROUTINE_SUCCESS'
export const UPDATE_ROUTINE_FAIL = 'UPDATE_ROUTINE_FAIL'

export const DELETING_ROUTINE = 'DELETING_ROUTINE'
export const DELETE_ROUTINE_SUCCESS = 'DELETE_ROUTINE_SUCCESS'
export const DELETE_ROUTINE_FAIL = 'DELETE_ROUTINE_FAIL'


/* WEEK ACTIONS */
export const SET_CURRENT_WEEK = "SET_CURRENT_WEEK"
export const WRITING_WEEK = "WRITING_WEEK"
export const CLEAR_CURRENT_WEEK = "CLEAR_CURRENT_WEEK"
export const INITIATE_WEEK = "INITIATE_WEEK"

// async
export const CREATING_WEEK = 'CREATING_WEEK'
export const CREATE_WEEK_SUCCESS = 'CREATE_WEEK_SUCCESS'
export const CREATE_WEEK_FAIL = 'CREATE_WEEK_FAIL'

export const FETCHING_WEEKS = 'FETCHING_WEEKS'
export const FETCH_WEEKS_SUCCESS = 'FETCH_WEEKS_SUCCESS'
export const FETCH_WEEKS_FAIL = 'FETCH_WEEKS_FAIL'

export const FETCHING_WEEK = 'FETCHING_WEEK'
export const FETCH_WEEK_SUCCESS = 'FETCH_WEEK_SUCCESS'
export const FETCH_WEEK_FAIL = 'FETCH_WEEK_FAIL'

export const UPDATING_WEEK = 'UPDATING_WEEK'
export const UPDATE_WEEK_SUCCESS = 'UPDATE_WEEK_SUCCESS'
export const UPDATE_WEEK_FAIL = 'UPDATE_WEEK_FAIL'

export const DELETING_WEEK = 'DELETING_WEEK'
export const DELETE_WEEK_SUCCESS = 'DELETE_WEEK_SUCCESS'
export const DELETE_WEEK_FAIL = 'DELETE_WEEK_FAIL'

/* SET_GROUP ACTIONS */
export const SET_CURRENT_SET_GROUP = "SET_CURRENT_SET_GROUP"
export const WRITING_CURRENT_SET_GROUP = "WRITING_CURRENT_SET_GROUP"
export const WRITING_CREATE_SET_GROUP_DATA = "WRITING_CREATE_SET_GROUP_DATA"
export const CLEAR_CREATE_SET_GROUP_DATA = "CLEAR_CREATE_SET_GROUP_DATA"
export const CLEAR_CURRENT_SET_GROUP = "CLEAR_CURRENT_SET_GROUP"
export const CLEAR_CHOSEN_EXERCISES = "CLEAR_CHOSEN_EXERCISES"

export const INITIATE_SET_GROUP = "INITIATE_SET_GROUP"
export const LOCK_IN_TYPE = "LOCK_IN_TYPE"
export const ADD_TO_CHOSEN_EXERCISES = "ADD_TO_CHOSEN_EXERCISES"
export const REMOVE_FROM_CHOSEN_EXERCISES = "REMOVE_FROM_CHOSEN_EXERCISES"
export const BULK_WRITE_CHOSEN_EXERCISES = "BULK_WRITE_CHOSEN_EXERCISES"

// asnync 
export const CREATING_SET_GROUP = 'CREATING_SET_GROUP'
export const CREATE_SET_GROUP_SUCCESS = 'CREATE_SET_GROUP_SUCCESS'
export const CREATE_SET_GROUP_FAIL = 'CREATE_SET_GROUP_FAIL'

export const UPDATING_SET_GROUP = 'UPDATING_SET_GROUP'
export const UPDATE_SET_GROUP_SUCCESS = 'UPDATE_SET_GROUP_SUCCESS'
export const UPDATE_SET_GROUP_FAIL = 'UPDATE_SET_GROUP_FAIL'

export const UPDATING_MANY_SET_GROUPS = 'UPDATING_MANY_SET_GROUPS'
export const UPDATE_MANY_SET_GROUPS_SUCCESS = 'UPDATE_MANY_SET_GROUPS_SUCCESS'
export const UPDATE_MANY_SET_GROUPS_FAIL = 'UPDATE_MANY_SET_GROUPS_FAIL'

export const FETCHING_SET_GROUPS = 'FETCHING_SET_GROUPS'
export const FETCH_SET_GROUPS_SUCCESS = 'FETCH_SET_GROUPS_SUCCESS'
export const FETCH_SET_GROUPS_FAIL = 'FETCH_SET_GROUPS_FAIL'

export const FETCHING_SET_GROUP = 'FETCHING_SET_GROUP'
export const FETCH_SET_GROUP_SUCCESS = 'FETCH_SET_GROUP_SUCCESS'
export const FETCH_SET_GROUP_FAIL = 'FETCH_SET_GROUP_FAIL'

export const DELETING_SET_GROUP = 'DELETING_SET_GROUP'
export const DELETE_SET_GROUP_SUCCESS = 'DELETE_SET_GROUP_SUCCESS'
export const DELETE_SET_GROUP_FAIL = 'DELETE_SET_GROUP_FAIL'

/* EXERCISE_SET ACTIONS */
export const SET_CURRENT_EXERCISE_SET = "SET_CURRENT_EXERCISE_SET"
export const SET_CURRENT_SET_GROUP_SETS = "SET_CURRENT_SET_GROUP_SETS"
export const WRITING_EXERCISE_SET = "WRITING_EXERCISE_SET"
export const CLEAR_CURRENT_EXERCISE_SET = "CLEAR_CURRENT_EXERCISE_SET"
export const INITIATE_EXERCISE_SET = "INITIATE_EXERCISE_SET"
export const CLEAR_CURRENT_EXERCISE_SETS = "CLEAR_CURRENT_EXERCISE_SETS"

// asnync 
export const CREATING_EXERCISE_SET = 'CREATING_EXERCISE_SET'
export const CREATE_EXERCISE_SET_SUCCESS = 'CREATE_EXERCISE_SET_SUCCESS'
export const CREATE_EXERCISE_SET_FAIL = 'CREATE_EXERCISE_SET_FAIL'

export const CREATING_EXERCISE_SETS = 'CREATING_EXERCISE_SETS'
export const CREATE_EXERCISE_SETS_SUCCESS = 'CREATE_EXERCISE_SETS_SUCCESS'
export const CREATE_EXERCISE_SETS_FAIL = 'CREATE_EXERCISE_SETS_FAIL'

export const UPDATING_EXERCISE_SET = 'UPDATING_EXERCISE_SET'
export const UPDATE_EXERCISE_SET_SUCCESS = 'UPDATE_EXERCISE_SET_SUCCESS'
export const UPDATE_EXERCISE_SET_FAIL = 'UPDATE_EXERCISE_SET_FAIL'

export const FETCHING_EXERCISE_SETS = 'FETCHING_EXERCISE_SETS'
export const FETCH_EXERCISE_SETS_SUCCESS = 'FETCH_EXERCISE_SETS_SUCCESS'
export const FETCH_EXERCISE_SETS_FAIL = 'FETCH_EXERCISE_SETS_FAIL'

export const FETCHING_EXERCISE_SET = 'FETCHING_EXERCISE_SET'
export const FETCH_EXERCISE_SET_SUCCESS = 'FETCH_EXERCISE_SET_SUCCESS'
export const FETCH_EXERCISE_SET_FAIL = 'FETCH_EXERCISE_SET_FAIL'

export const DELETING_EXERCISE_SET = 'DELETING_EXERCISE_SET'
export const DELETE_EXERCISE_SET_SUCCESS = 'DELETE_EXERCISE_SET_SUCCESS'
export const DELETE_EXERCISE_SET_FAIL = 'DELETE_EXERCISE_SET_FAIL'

/* 
============================================================================
============================================================================
------------------ RECYCLED ACTIONS ----------------------------------------
============================================================================
============================================================================
*/

/* 
// non async
export const SET_CURRENT_ROUTINE =  'SET_CURRENT_ROUTINE'
export const SET_CURRENT_WEEK = 'SET_CURRENT_WEEK'
export const SET_CURRENT_EXERCISE_SET = 'SET_CURRENT_EXERCISE_SET'

export const EDITNIG_ROUTINE_HEADER = 'EDITNIG_ROUTINE_HEADER'
export const EDITING_WEEK = 'EDITING_WEEK'
export const EDITING_EXERCISE_SET = 'EDITING_EXERCISE_SET'

export const RESET_ROUTINE = 'RESET_ROUTINE'

export const SET_SEARCHING_WEEK = 'SET_SEARCHING_WEEK'
export const SET_EDITING_MODE = 'SET_EDITING_MODE'


export const FETCHING_PRODUCTS = 'FETCHING_PRODUCTS'
export const FETCH_PRODUCTS_SUCCESS = 'FETCH_PRODUCTS_SUCCESS'
export const FETCH_PRODUCTS_FAIL = 'FETCH_PRODUCTS_FAIL'

export const FETCHING_PRODUCT = 'FETCHING_PRODUCT'
export const FETCH_PRODUCT_SUCCESS = 'FETCH_PRODUCT_SUCCESS'
export const FETCH_PRODUCT_FAIL = 'FETCH_PRODUCT_FAIL'

export const SET_CURRENT_PRODUCT = 'SET_CURRENT_PRODUCT'

export const FETCHING_RELATED_PRODUCTS = 'FETCHING_RELATED_PRODUCTS'
export const FETCH_RELATED_SUCCESS = 'FETCH_RELATED_SUCCESS'
export const FETCH_RELATED_FAIL = 'FETCH_RELATED_FAIL'

export const SET_SEARCH_TERM = 'SET_SEARCH_TERM'

export const CLEAR_PRODUCT_SEARCH_RESULTS = 'CLEAR_PRODUCT_SEARCH_RESULTS'



export const FETCHING_LOCATION = 'FETCHING_LOCATION'
export const FETCH_LOCATION_SUCCES = 'FETCH_LOCATION_SUCCES'
export const FETCH_LOCATION_FAIL = 'FETCH_LOCATION_FAIL'

export const FETCHING_LOCATIONS = 'FETCHING_LOCATIONS'
export const FETCH_LOCATIONS_SUCCES = 'FETCH_LOCATIONS_SUCCES'
export const FETCH_LOCATIONS_FAIL = 'FETCH_LOCATIONS_FAIL'

export const SET_CURRENT_STORE = 'SET_CURRENT_STORE'
export const SET_CHANGING_HOME_STORE = 'SET_CHANGING_HOME_STORE'

export const SET_SEARCH_ZIP = 'SET_ZIP'

export const CLEAR_LOCATION_LIST = 'CLEAR_LOCATION_LIST'

export const SETTING_HOME_STORE = 'SETTING_HOME_STORE'
export const SET_HOME_STORE_SUCCESS = 'SET_HOME_STORE_SUCCESS'
export const SET_HOME_STORE_FAIL = 'SET_HOME_STORE_FAIL'




export const FETCHING_CART = 'FETCHING_CART'
export const FETCH_CART_SUCCES = 'FETCH_SUCCES'
export const FETCH_CART_FAIL = 'FETCH_FAIL'

export const ADD_ITEM_TO_CART = 'ADD_ITEM_TO_CART'
export const REMOVE_ITEM_FROM_CART = 'REMOVE_ITEM_FROM_CART'
export const CHANGE_ITEM_QUANTITY = 'CHANGE_ITEM_QUANTITY'

export const CLEAR_CART = 'CLEAR_CART'

export const POSTING_CART = 'POSTING_CART'
export const POSTING_CART_SUCCESS = 'POSTING_CART_SUCCESS'
export const POSTING_CART_FAIL = 'POSTING_CART_FAIL'
 */